function T = get_features_all_win(vel, flu, acc, rpm, tps, map, va, th_urb, th_rur,w)

vel_win_feat_all = get_feat_from_windows(vel, vel, th_urb, th_rur, w);
flu_win_feat_all = get_feat_from_windows(flu, vel, th_urb, th_rur, w);
acc_win_feat_all = get_feat_from_windows(acc, vel, th_urb, th_rur, w);
rpm_win_feat_all = get_feat_from_windows(rpm, vel, th_urb, th_rur, w);
tps_win_feat_all = get_feat_from_windows(tps, vel, th_urb, th_rur, w);
map_win_feat_all = get_feat_from_windows(map, vel, th_urb, th_rur, w);
va_win_feat_all = get_feat_from_windows(va, vel, th_urb, th_rur, w);
t = min([length(vel_win_feat_all), ...
            length(flu_win_feat_all), ...
            length(acc_win_feat_all), ...
            length(rpm_win_feat_all), ...
            length(tps_win_feat_all), ...
            length(map_win_feat_all), ...
            length(va_win_feat_all)]);
win_feat_all = [  vel_win_feat_all(1:t,:), ...
                    flu_win_feat_all(1:t,:), ...
                    acc_win_feat_all(1:t,:), ...
                    rpm_win_feat_all(1:t,:), ...
                    tps_win_feat_all(1:t,:), ...
                    map_win_feat_all(1:t,:), ...
                    va_win_feat_all(1:t,:), ...
                    ];

unique_win_feat_all = win_feat_all(:, setdiff(1:size(win_feat_all,2), 4:3:size(win_feat_all)));%unique(win_feat_all', 'rows')';

T = array2table(unique_win_feat_all, 'VariableNames',{'umbral_rde','vel_mean', 'vel_std' ...
                                                ,'flu_mean', 'flu_std' ...
                                                ,'acc_mean', 'acc_std' ...
                                                ,'rpm_mean', 'rpm_std' ...
                                                ,'tps_mean', 'tps_std' ...
                                                ,'map_mean', 'map_std' ...
                                                ,'va_mean', 'va_std' ...
                                                });
